# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(498, 505)
        Dialog.setStyleSheet("QDialog {background-color:rgb(255, 255, 255);background-image: url("
                             ":/icons/background_2.bmp);}QLabel{color:rgb(255, 255, 255);font: 10pt "
                             "\"楷体\";}QPushButton{background-color:rgba(255, 255, 255, "
                             "200);border:none;border-radius:5px;font: 10pt \"楷体\";min-width:130px;color:rgb(0, 0, "
                             "0)}QPushButton:hover{background-color:rgba(255, 255, 255, 150);}\n"
                             "QPushButton:disabled{background-color:rgba(255, 255, 255, 150);color:rgba(255, 255, 255, 180);}\n"
                             "QMessageBox QPushButton:hover{background-color:rgba(255, 255, 255, 150);}\n"
                             "QMessageBox QPushButton{background-color:rgba(255, 255, 255, "
                             "200);border:none;border-radius:5px;font: 10pt "
                             "\"楷体\";min-width:130px;min-height:28px;color:rgb(0, 0, 0)}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 3)
        self.edit_a = QtWidgets.QPushButton(Dialog)
        self.edit_a.setMinimumSize(QtCore.QSize(130, 28))
        self.edit_a.setObjectName("edit_a")
        self.gridLayout.addWidget(self.edit_a, 7, 2, 1, 1)
        self.label_limit = QtWidgets.QLabel(Dialog)
        self.label_limit.setObjectName("label_limit")
        self.gridLayout.addWidget(self.label_limit, 8, 1, 1, 1)
        self.label_h = QtWidgets.QLabel(Dialog)
        self.label_h.setObjectName("label_h")
        self.gridLayout.addWidget(self.label_h, 6, 1, 1, 1)
        self.edit_limit = QtWidgets.QPushButton(Dialog)
        self.edit_limit.setMinimumSize(QtCore.QSize(130, 28))
        self.edit_limit.setObjectName("edit_limit")
        self.gridLayout.addWidget(self.edit_limit, 8, 2, 1, 1)
        self.label_bx = QtWidgets.QLabel(Dialog)
        self.label_bx.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_bx.setObjectName("label_bx")
        self.gridLayout.addWidget(self.label_bx, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setMinimumSize(QtCore.QSize(130, 28))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 9, 2, 1, 1)
        self.label_w = QtWidgets.QLabel(Dialog)
        self.label_w.setObjectName("label_w")
        self.gridLayout.addWidget(self.label_w, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.label_cell_width = QtWidgets.QLabel(Dialog)
        self.label_cell_width.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_cell_width.setObjectName("label_cell_width")
        self.gridLayout.addWidget(self.label_cell_width, 2, 1, 1, 1)
        self.edit_w = QtWidgets.QPushButton(Dialog)
        self.edit_w.setMinimumSize(QtCore.QSize(130, 28))
        self.edit_w.setObjectName("edit_w")
        self.gridLayout.addWidget(self.edit_w, 5, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_path = QtWidgets.QLabel(Dialog)
        self.label_path.setObjectName("label_path")
        self.gridLayout.addWidget(self.label_path, 9, 1, 1, 1)
        self.edit_h = QtWidgets.QPushButton(Dialog)
        self.edit_h.setMinimumSize(QtCore.QSize(130, 28))
        self.edit_h.setObjectName("edit_h")
        self.gridLayout.addWidget(self.edit_h, 6, 2, 1, 1)
        self.label_by = QtWidgets.QLabel(Dialog)
        self.label_by.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_by.setObjectName("label_by")
        self.gridLayout.addWidget(self.label_by, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 44))
        self.buttonBox.setStyleSheet(
            "QPushButton{background-color:rgba(255, 255, 255, 200);border:none;border-radius:5px;font: 10pt \"楷体\";min-height:28px;min-width:105px;color:rgb(0, 0, 0)}QPushButton:hover{background-color:rgba(255, 255, 255, 150);}")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 10, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.label_a = QtWidgets.QLabel(Dialog)
        self.label_a.setObjectName("label_a")
        self.gridLayout.addWidget(self.label_a, 7, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 3)
        self.edit_bx = QtWidgets.QPushButton(Dialog)
        self.edit_bx.setMinimumSize(QtCore.QSize(130, 50))
        self.edit_bx.setObjectName("edit_bx")
        self.gridLayout.addWidget(self.edit_bx, 2, 2, 3, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_9.setText(_translate("Dialog", "请在修改 每个格子的宽度、bx、by前先确保高度、宽"))
        self.edit_a.setText(_translate("Dialog", "修改"))
        self.label_limit.setText(_translate("Dialog", "TextLabel"))
        self.label_h.setText(_translate("Dialog", "TextLabel"))
        self.edit_limit.setText(_translate("Dialog", "修改"))
        self.label_bx.setText(_translate("Dialog", "TextLabel"))
        self.label.setText(_translate("Dialog", "宽度："))
        self.label_3.setText(_translate("Dialog", "总雷数："))
        self.pushButton.setText(_translate("Dialog", "选择文件"))
        self.label_w.setText(_translate("Dialog", "TextLabel"))
        self.label_8.setText(_translate("Dialog", "扫雷路径："))
        self.label_2.setText(_translate("Dialog", "高度："))
        self.label_cell_width.setText(_translate("Dialog", "TextLabel"))
        self.edit_w.setText(_translate("Dialog", "修改"))
        self.label_4.setText(_translate("Dialog", "每个格子的宽度："))
        self.label_5.setText(_translate("Dialog", "by："))
        self.label_path.setText(_translate("Dialog", "TextLabel"))
        self.edit_h.setText(_translate("Dialog", "修改"))
        self.label_by.setText(_translate("Dialog", "TextLabel"))
        self.label_6.setText(_translate("Dialog", "bx："))
        self.label_7.setText(_translate("Dialog", "limit："))
        self.label_a.setText(_translate("Dialog", "TextLabel"))
        self.label_10.setText(_translate("Dialog", "度，输入正确，修改后记得要重新截图哦。"))
        self.edit_bx.setText(_translate("Dialog", "修改"))


import bg_rc
