# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screenshot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(398, 443)
        form.setMinimumSize(QtCore.QSize(398, 443))
        form.setMaximumSize(QtCore.QSize(398, 443))
        form.setStyleSheet(
            "#frame_5{background-image: url(:/icons/background_2.bmp);border:none}"
        )
        self.verticalLayout = QtWidgets.QVBoxLayout(form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(form)
        self.frame_5.setStyleSheet(
            'QLabel{color:rgb(255, 255, 255);font: 10pt "楷体";}\n'
            'QPushButton{background-color:rgba(255, 255, 255, 200);color:rgb(0, 0, 0);border:none;border-radius:5px;font: 10pt "楷体";min-height:28px;min-width:105px;}\n'
            "QPushButton:hover{background-color:rgba(255, 255, 255, 150);color:rgb(8, 75, 176)}"
        )
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(-1, -1, 12, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.img_label = QtWidgets.QLabel(self.frame_4)
        self.img_label.setMinimumSize(QtCore.QSize(100, 140))
        self.img_label.setMaximumSize(QtCore.QSize(100, 140))
        self.img_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.img_label.setStyleSheet("")
        self.img_label.setObjectName("img_label")
        self.horizontalLayout_3.addWidget(self.img_label)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setMinimumSize(QtCore.QSize(372, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_i = QtWidgets.QLabel(self.frame)
        self.label_i.setMinimumSize(QtCore.QSize(81, 26))
        self.label_i.setObjectName("label_i")
        self.gridLayout_2.addWidget(self.label_i, 0, 0, 1, 1)
        self.lineEdit_i = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_i.setMinimumSize(QtCore.QSize(80, 26))
        self.lineEdit_i.setObjectName("lineEdit_i")
        self.gridLayout_2.addWidget(self.lineEdit_i, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(81, 26))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.lineEdit_j = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_j.setMinimumSize(QtCore.QSize(80, 26))
        self.lineEdit_j.setObjectName("lineEdit_j")
        self.gridLayout_2.addWidget(self.lineEdit_j, 0, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(-1, 8, -1, 8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox_name = QtWidgets.QComboBox(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("楷体")
        self.comboBox_name.setFont(font)
        self.comboBox_name.setObjectName("comboBox_name")
        self.horizontalLayout_2.addWidget(self.comboBox_name)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_img = QtWidgets.QPushButton(self.frame_2)
        self.save_img.setObjectName("save_img")
        self.horizontalLayout.addWidget(self.save_img)
        self.re_screenshot = QtWidgets.QPushButton(self.frame_2)
        self.re_screenshot.setObjectName("re_screenshot")
        self.horizontalLayout.addWidget(self.re_screenshot)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame_5)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Form"))
        self.img_label.setText(_translate("form", "等待截图"))
        self.label_i.setText(_translate("form", "横坐标："))
        self.label_3.setText(_translate("form", "纵坐标："))
        self.label.setText(_translate("form", "文件名："))
        self.save_img.setText(_translate("form", "保存图片"))
        self.re_screenshot.setText(_translate("form", "截图"))


import bg_rc
